name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json
  sync-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-demo
        run: go build ./cmd/baton-demo
      - name: Initialize database
        run: ./baton-demo --init-db
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-demo
          baton-entitlement: 'group:group-0000000:member'
          baton-principal: 'user-0000000'
          baton-principal-type: 'user'
